PROJECT_DEFS := RADIO_MODE_UART_CRSF
# PROJECT_DEFS := RADIO_MODE_UART
# PROJECT_DEFS := RADIO_MODE_PPM



# STM32 CONFIGS
DEVICE_FAMILY  := STM32F1xx
DEVICE_TYPE    := STM32F103xx
DEVICE_DEF     := STM32F103xE
DEVICE         := STM32F103RC

ARM_CPU   := -mcpu=cortex-m3
ARM_FPU   :=
FLOAT_ABI :=


CUBE_LOCATION := cube/STM32F103RCT6
LINKER_FILE := $(CUBE_LOCATION)/STM32F103RCTx_FLASH.ld