/*$file${.::src::sumo_hsm.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: sumo_hsm.qm
* File:  ${.::src::sumo_hsm.c}
*
* This code has been generated by QM 5.2.2 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This code is covered by the following QP license:
* License #    : QM-EVAL-QPC
* Issued to    : Users of QP/C Real-Time Embedded Framework (RTEF)
* Framework(s) : qpc
* Support ends : 2023-12-31
* License scope:
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is free software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${.::src::sumo_hsm.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include <math.h>
#include <stdio.h>
#include "qf_custom_defines.h"
#include "qpc.h"    /* QP/C framework API */
#include "bsp.h"    /* Board Support Package interface */
#include "led_service.h"
#include "driving_service.h"
#include "buzzer_service.h"
#include "radio_service.h"
#include "distance_service.h"
#include "adc_service.h"
#include "bsp_eeprom.h"
#include "ble_service.h"
#include "parameters.h"

#define CALIB_ANGLE_MULT    2.5
#ifndef M_PI
#define M_PI                3.14159265
#endif

#define MAX_STRATEGIES        2
#define MAX_PRE_STRATEGIES    3

static sumo_parameters_t parameters;

/* ask QM to declare the Blinky class --------------------------------------*/
/*$declare${AOs::SumoHSM} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::SumoHSM} ..........................................................*/
typedef struct {
/* protected: */
    QMActive super;

/* private: */
    QTimeEvt timeEvt;
    QTimeEvt buzzerTimeEvt;
    uint8_t buzzerCount;
    uint8_t strategy;
    QTimeEvt timeEvt_2;
    uint8_t pre_strategy;
    QTimeEvt timeEvtBle;
    uint8_t ble_counter;

/* private submachines */
    /* exit points for submachine ${AOs::SumoHSM::SM::LineSubmachine} */
    struct SM_LineSubmachine {
        QMState super;
        QActionHandler const XP1; /* eXit-Point segment */
        QActionHandler const STOP; /* eXit-Point segment */
    } const *sub_LineSubmachine;
    /* exit points for submachine ${AOs::SumoHSM::SM::PreStrategy} */
    struct SM_PreStrategy {
        QMState super;
        QActionHandler const XP1; /* eXit-Point segment */
    } const *sub_PreStrategy;
} SumoHSM;

/* protected: */
static QState SumoHSM_initial(SumoHSM * const me, void const * const par);
static QState SumoHSM_Idle  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_Idle_e(SumoHSM * const me);
static QState SumoHSM_Idle_x(SumoHSM * const me);
static QMState const SumoHSM_Idle_s = {
    QM_STATE_NULL, /* superstate (top) */
    Q_STATE_CAST(&SumoHSM_Idle),
    Q_ACTION_CAST(&SumoHSM_Idle_e),
    Q_ACTION_CAST(&SumoHSM_Idle_x),
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_RCWait  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_RCWait_e(SumoHSM * const me);
static QState SumoHSM_RCWait_x(SumoHSM * const me);
static QMState const SumoHSM_RCWait_s = {
    QM_STATE_NULL, /* superstate (top) */
    Q_STATE_CAST(&SumoHSM_RCWait),
    Q_ACTION_CAST(&SumoHSM_RCWait_e),
    Q_ACTION_CAST(&SumoHSM_RCWait_x),
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_StarStrategy  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_StarStrategy_e(SumoHSM * const me);
static QMState const SumoHSM_StarStrategy_s = {
    QM_STATE_NULL, /* superstate (top) */
    Q_STATE_CAST(&SumoHSM_StarStrategy),
    Q_ACTION_CAST(&SumoHSM_StarStrategy_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_AutoWait  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_AutoWait_e(SumoHSM * const me);
static QMState const SumoHSM_AutoWait_s = {
    QM_STATE_NULL, /* superstate (top) */
    Q_STATE_CAST(&SumoHSM_AutoWait),
    Q_ACTION_CAST(&SumoHSM_AutoWait_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_StepsStrategy  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_StepsStrategy_e(SumoHSM * const me);
static QState SumoHSM_StepsStrategy_x(SumoHSM * const me);
static QMState const SumoHSM_StepsStrategy_s = {
    QM_STATE_NULL, /* superstate (top) */
    Q_STATE_CAST(&SumoHSM_StepsStrategy),
    Q_ACTION_CAST(&SumoHSM_StepsStrategy_e),
    Q_ACTION_CAST(&SumoHSM_StepsStrategy_x),
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_RC  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_RC_e(SumoHSM * const me);
static QMState const SumoHSM_RC_s = {
    QM_STATE_NULL, /* superstate (top) */
    Q_STATE_CAST(&SumoHSM_RC),
    Q_ACTION_CAST(&SumoHSM_RC_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_line1  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_line1_e(SumoHSM * const me);
static QState SumoHSM_line1_XP1(SumoHSM * const me);
static QState SumoHSM_line1_STOP(SumoHSM * const me);
static struct SM_LineSubmachine const SumoHSM_line1_s = {
    {
        QM_STATE_NULL, /* superstate (top) */
        Q_STATE_CAST(&SumoHSM_line1),
        Q_ACTION_CAST(&SumoHSM_line1_e),
        Q_ACTION_NULL, /* no exit action */
        Q_ACTION_NULL  /* no initial tran. */
    }
    ,Q_ACTION_CAST(&SumoHSM_line1_XP1)
    ,Q_ACTION_CAST(&SumoHSM_line1_STOP)
};
static QState SumoHSM_line2  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_line2_e(SumoHSM * const me);
static QState SumoHSM_line2_XP1(SumoHSM * const me);
static QState SumoHSM_line2_STOP(SumoHSM * const me);
static struct SM_LineSubmachine const SumoHSM_line2_s = {
    {
        QM_STATE_NULL, /* superstate (top) */
        Q_STATE_CAST(&SumoHSM_line2),
        Q_ACTION_CAST(&SumoHSM_line2_e),
        Q_ACTION_NULL, /* no exit action */
        Q_ACTION_NULL  /* no initial tran. */
    }
    ,Q_ACTION_CAST(&SumoHSM_line2_XP1)
    ,Q_ACTION_CAST(&SumoHSM_line2_STOP)
};
static QState SumoHSM_pre_strategy  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_pre_strategy_e(SumoHSM * const me);
static QState SumoHSM_pre_strategy_XP1(SumoHSM * const me);
static struct SM_PreStrategy const SumoHSM_pre_strategy_s = {
    {
        QM_STATE_NULL, /* superstate (top) */
        Q_STATE_CAST(&SumoHSM_pre_strategy),
        Q_ACTION_CAST(&SumoHSM_pre_strategy_e),
        Q_ACTION_NULL, /* no exit action */
        Q_ACTION_NULL  /* no initial tran. */
    }
    ,Q_ACTION_CAST(&SumoHSM_pre_strategy_XP1)
};

/* submachine ${AOs::SumoHSM::SM::LineSubmachine} */
static QState SumoHSM_LineSubmachine  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_LineSubmachine_x(SumoHSM * const me);
static QState SumoHSM_LineSubmachine_i(SumoHSM * const me);
static QMState const SumoHSM_LineSubmachine_s = {
    QM_STATE_NULL, /* superstate unused */
    Q_STATE_CAST(&SumoHSM_LineSubmachine),
    Q_ACTION_NULL, /* no entry action */
    Q_ACTION_CAST(&SumoHSM_LineSubmachine_x),
    Q_ACTION_CAST(&SumoHSM_LineSubmachine_i)
};
static QState SumoHSM_LineSubmachine_LineGoBack  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_LineSubmachine_LineGoBack_e(SumoHSM * const me);
static QMState const SumoHSM_LineSubmachine_LineGoBack_s = {
    &SumoHSM_LineSubmachine_s, /* superstate */
    Q_STATE_CAST(&SumoHSM_LineSubmachine_LineGoBack),
    Q_ACTION_CAST(&SumoHSM_LineSubmachine_LineGoBack_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_LineSubmachine_LineTurnRight  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_LineSubmachine_LineTurnRight_e(SumoHSM * const me);
static QState SumoHSM_LineSubmachine_LineTurnRight_x(SumoHSM * const me);
static QMState const SumoHSM_LineSubmachine_LineTurnRight_s = {
    &SumoHSM_LineSubmachine_s, /* superstate */
    Q_STATE_CAST(&SumoHSM_LineSubmachine_LineTurnRight),
    Q_ACTION_CAST(&SumoHSM_LineSubmachine_LineTurnRight_e),
    Q_ACTION_CAST(&SumoHSM_LineSubmachine_LineTurnRight_x),
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_LineSubmachine_LineTurnLeft  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_LineSubmachine_LineTurnLeft_e(SumoHSM * const me);
static QState SumoHSM_LineSubmachine_LineTurnLeft_x(SumoHSM * const me);
static QMState const SumoHSM_LineSubmachine_LineTurnLeft_s = {
    &SumoHSM_LineSubmachine_s, /* superstate */
    Q_STATE_CAST(&SumoHSM_LineSubmachine_LineTurnLeft),
    Q_ACTION_CAST(&SumoHSM_LineSubmachine_LineTurnLeft_e),
    Q_ACTION_CAST(&SumoHSM_LineSubmachine_LineTurnLeft_x),
    Q_ACTION_NULL  /* no initial tran. */
};

/* submachine ${AOs::SumoHSM::SM::PreStrategy} */
static QState SumoHSM_PreStrategy  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_PreStrategy_e(SumoHSM * const me);
static QState SumoHSM_PreStrategy_x(SumoHSM * const me);
static QMState const SumoHSM_PreStrategy_s = {
    QM_STATE_NULL, /* superstate unused */
    Q_STATE_CAST(&SumoHSM_PreStrategy),
    Q_ACTION_CAST(&SumoHSM_PreStrategy_e),
    Q_ACTION_CAST(&SumoHSM_PreStrategy_x),
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_PreStrategy_EP0_ep(SumoHSM * const me);
static QState SumoHSM_PreStrategy_EP1_ep(SumoHSM * const me);
static QState SumoHSM_PreStrategy_EP2_ep(SumoHSM * const me);
static QState SumoHSM_PreStrategy_EP3_ep(SumoHSM * const me);
static QState SumoHSM_PreStrategy_PreStrategy_0  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_PreStrategy_PreStrategy_0_e(SumoHSM * const me);
static QMState const SumoHSM_PreStrategy_PreStrategy_0_s = {
    &SumoHSM_PreStrategy_s, /* superstate */
    Q_STATE_CAST(&SumoHSM_PreStrategy_PreStrategy_0),
    Q_ACTION_CAST(&SumoHSM_PreStrategy_PreStrategy_0_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_PreStrategy_PreStrategy_2  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_PreStrategy_PreStrategy_2_e(SumoHSM * const me);
static QMState const SumoHSM_PreStrategy_PreStrategy_2_s = {
    &SumoHSM_PreStrategy_s, /* superstate */
    Q_STATE_CAST(&SumoHSM_PreStrategy_PreStrategy_2),
    Q_ACTION_CAST(&SumoHSM_PreStrategy_PreStrategy_2_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_PreStrategy_PreStrategy_3  (SumoHSM * const me, QEvt const * const e);
static QMState const SumoHSM_PreStrategy_PreStrategy_3_s = {
    &SumoHSM_PreStrategy_s, /* superstate */
    Q_STATE_CAST(&SumoHSM_PreStrategy_PreStrategy_3),
    Q_ACTION_NULL, /* no entry action */
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_PreStrategy_PreStrategy_1  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_PreStrategy_PreStrategy_1_e(SumoHSM * const me);
static QMState const SumoHSM_PreStrategy_PreStrategy_1_s = {
    &SumoHSM_PreStrategy_s, /* superstate */
    Q_STATE_CAST(&SumoHSM_PreStrategy_PreStrategy_1),
    Q_ACTION_CAST(&SumoHSM_PreStrategy_PreStrategy_1_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_PreStrategy_pre_strategy_1_sub2  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_PreStrategy_pre_strategy_1_sub2_e(SumoHSM * const me);
static QMState const SumoHSM_PreStrategy_pre_strategy_1_sub2_s = {
    &SumoHSM_PreStrategy_s, /* superstate */
    Q_STATE_CAST(&SumoHSM_PreStrategy_pre_strategy_1_sub2),
    Q_ACTION_CAST(&SumoHSM_PreStrategy_pre_strategy_1_sub2_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_PreStrategy_pre_strategy_1_sub1  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_PreStrategy_pre_strategy_1_sub1_e(SumoHSM * const me);
static QMState const SumoHSM_PreStrategy_pre_strategy_1_sub1_s = {
    &SumoHSM_PreStrategy_s, /* superstate */
    Q_STATE_CAST(&SumoHSM_PreStrategy_pre_strategy_1_sub1),
    Q_ACTION_CAST(&SumoHSM_PreStrategy_pre_strategy_1_sub1_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_PreStrategy_pre_strategy_2_sub1  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_PreStrategy_pre_strategy_2_sub1_e(SumoHSM * const me);
static QMState const SumoHSM_PreStrategy_pre_strategy_2_sub1_s = {
    &SumoHSM_PreStrategy_s, /* superstate */
    Q_STATE_CAST(&SumoHSM_PreStrategy_pre_strategy_2_sub1),
    Q_ACTION_CAST(&SumoHSM_PreStrategy_pre_strategy_2_sub1_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
static QState SumoHSM_PreStrategy_pre_strategy_2_sub2  (SumoHSM * const me, QEvt const * const e);
static QState SumoHSM_PreStrategy_pre_strategy_2_sub2_e(SumoHSM * const me);
static QMState const SumoHSM_PreStrategy_pre_strategy_2_sub2_s = {
    &SumoHSM_PreStrategy_s, /* superstate */
    Q_STATE_CAST(&SumoHSM_PreStrategy_pre_strategy_2_sub2),
    Q_ACTION_CAST(&SumoHSM_PreStrategy_pre_strategy_2_sub2_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
/*$enddecl${AOs::SumoHSM} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

static void SumoHSM_change_strategy(SumoHSM * const me);

/* instantiate the Blinky active object ------------------------------------*/
static SumoHSM l_sumo_hsm;
QActive * const AO_SumoHSM = &l_sumo_hsm.super.super;

/* ask QM to define the Blinky class ---------------------------------------*/
/*$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/* Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.9.0 or higher required
#endif
/*$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$define${AOs::SumoHSM_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::SumoHSM_ctor} .....................................................*/
void SumoHSM_ctor(void) {
    SumoHSM *me = (SumoHSM *)AO_SumoHSM;
    QMActive_ctor(&me->super, Q_STATE_CAST(&SumoHSM_initial));
    QTimeEvt_ctorX(&me->timeEvt, &me->super.super, TIMEOUT_SIG, 0U);
    QTimeEvt_ctorX(&me->timeEvt_2, &me->super.super, TIMEOUT_2_SIG, 0U);
    QTimeEvt_ctorX(&me->timeEvtBle, &me->super.super, TIMEOUT_SEND_BLE_SIG, 0U);
    QTimeEvt_ctorX(&me->buzzerTimeEvt, &me->super.super, PLAY_BUZZER_SIG, 0U);
    me->ble_counter = 0;
    parameters_init(&parameters);

}
/*$enddef${AOs::SumoHSM_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

static void SumoHSM_change_strategy(SumoHSM * const me) {
    me->strategy++;
    if (me->strategy >= MAX_STRATEGIES){
        me->strategy = 0;
    }
}

static void SumoHSM_change_pre_strategy(SumoHSM * const me) {
    me->pre_strategy++;
    if (me->pre_strategy >= MAX_PRE_STRATEGIES){
        me->pre_strategy = 0;
    }
}

/*$define${AOs::SumoHSM} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::SumoHSM} ..........................................................*/

/*${AOs::SumoHSM::SM} ......................................................*/
static QState SumoHSM_initial(SumoHSM * const me, void const * const par) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { /* tran-action table */
        &SumoHSM_Idle_s, /* target state */
        {
            Q_ACTION_CAST(&SumoHSM_Idle_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    /*${AOs::SumoHSM::SM::initial} */
    (void)par; /* unused parameter */
    /* arm the private time event to expire in 1/2s
    * and periodically every 1/2 second
    */
    QTimeEvt_armX(&me->buzzerTimeEvt, BSP_TICKS_PER_SEC/10, 0);

    me->buzzerCount = 0U;

    QS_FUN_DICTIONARY(&SumoHSM_Idle);
    QS_FUN_DICTIONARY(&SumoHSM_RCWait);
    QS_FUN_DICTIONARY(&SumoHSM_StarStrategy);
    QS_FUN_DICTIONARY(&SumoHSM_AutoWait);
    QS_FUN_DICTIONARY(&SumoHSM_StepsStrategy);
    QS_FUN_DICTIONARY(&SumoHSM_RC);
    QS_FUN_DICTIONARY(&SumoHSM_line1);
    QS_FUN_DICTIONARY(&SumoHSM_line2);
    QS_FUN_DICTIONARY(&SumoHSM_pre_strategy);
    QS_FUN_DICTIONARY(&SumoHSM_LineSubmachine_LineGoBack);
    QS_FUN_DICTIONARY(&SumoHSM_LineSubmachine_LineTurnRight);
    QS_FUN_DICTIONARY(&SumoHSM_LineSubmachine_LineTurnLeft);
    QS_FUN_DICTIONARY(&SumoHSM_PreStrategy_PreStrategy_0);
    QS_FUN_DICTIONARY(&SumoHSM_PreStrategy_PreStrategy_2);
    QS_FUN_DICTIONARY(&SumoHSM_PreStrategy_PreStrategy_3);
    QS_FUN_DICTIONARY(&SumoHSM_PreStrategy_PreStrategy_1);
    QS_FUN_DICTIONARY(&SumoHSM_PreStrategy_pre_strategy_1_sub2);
    QS_FUN_DICTIONARY(&SumoHSM_PreStrategy_pre_strategy_1_sub1);
    QS_FUN_DICTIONARY(&SumoHSM_PreStrategy_pre_strategy_2_sub1);
    QS_FUN_DICTIONARY(&SumoHSM_PreStrategy_pre_strategy_2_sub2);
    QS_FUN_DICTIONARY(&SumoHSM_LineSubmachine);
    QS_FUN_DICTIONARY(&SumoHSM_PreStrategy);

    return QM_TRAN_INIT(&tatbl_);
}

/*${AOs::SumoHSM::SM::Idle} ................................................*/
/*${AOs::SumoHSM::SM::Idle} */
static QState SumoHSM_Idle_e(SumoHSM * const me) {
    board_led_off();
    driving_disable();
    drive(0,0);
    me->strategy = 0;
    me->pre_strategy = 0;
    QTimeEvt_disarm(&me->timeEvt);
    QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_SEC/2, BSP_TICKS_PER_SEC/2);

    if (adc_get_low_battery()){
        led_stripe_set_all(color_red);
    }
    return QM_ENTRY(&SumoHSM_Idle_s);
}
/*${AOs::SumoHSM::SM::Idle} */
static QState SumoHSM_Idle_x(SumoHSM * const me) {
    QTimeEvt_disarm(&me->timeEvt);
    QTimeEvt_disarm(&me->buzzerTimeEvt);
    buzzer_stop();
    bsp_ble_start();
    return QM_EXIT(&SumoHSM_Idle_s);
}
/*${AOs::SumoHSM::SM::Idle} */
static QState SumoHSM_Idle(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::Idle::TIMEOUT} */
        case TIMEOUT_SIG: {
            board_led_toggle();
            status_ = QM_HANDLED();
            break;
        }
        /*${AOs::SumoHSM::SM::Idle::CHANGE_STATE_EVT} */
        case CHANGE_STATE_EVT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_AutoWait_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_Idle_x), /* exit */
                    Q_ACTION_CAST(&SumoHSM_AutoWait_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::Idle::PLAY_BUZZER} */
        case PLAY_BUZZER_SIG: {
            buzzer_toggle();

            if (me->buzzerCount == 15) {
                QTimeEvt_armX(&me->buzzerTimeEvt, 1.6 * BSP_TICKS_PER_SEC, 0);
                led_stripe_set(me->buzzerCount, color_purple);
            } else if (me->buzzerCount < 15){
                QTimeEvt_armX(&me->buzzerTimeEvt, BSP_TICKS_PER_SEC/10, 0);
                led_stripe_set(me->buzzerCount, color_purple);
            } else{
                buzzer_stop();
                bsp_ble_start();
            }


            me->buzzerCount += 1;
            status_ = QM_HANDLED();
            break;
        }
        /*${AOs::SumoHSM::SM::Idle::LOW_BATTERY} */
        case LOW_BATTERY_SIG: {
            led_stripe_set_all(color_red);
            status_ = QM_HANDLED();
            break;
        }
        /*${AOs::SumoHSM::SM::Idle::BLE_DATA} */
        case BLE_DATA_SIG: {
            ble_data_header_t last_header = ble_service_last_packet_type();

            if (last_header == BLE_REQUEST_DATA){
                me->ble_counter = 0;
                QTimeEvt_armX(&me->timeEvtBle, BSP_TICKS_PER_MILISSEC * 10, 0);
            } else if (last_header == BLE_UPDATE_PARAMETERS) {
                ble_rcv_packet_t last_data;
                ble_service_last_packet(&last_data);
                parameters_update_from_ble(&parameters, last_data._raw);
            }
            status_ = QM_HANDLED();
            break;
        }
        /*${AOs::SumoHSM::SM::Idle::TIMEOUT_SEND_BLE} */
        case TIMEOUT_SEND_BLE_SIG: {
            if (me->ble_counter < 8){
                parameters_report(parameters, me->ble_counter);
                QTimeEvt_armX(&me->timeEvtBle, BSP_TICKS_PER_MILISSEC * 10, 0);
            }

            me->ble_counter++;
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::RCWait} ..............................................*/
/*${AOs::SumoHSM::SM::RCWait} */
static QState SumoHSM_RCWait_e(SumoHSM * const me) {
    board_led_off();
    drive(0,0);
    driving_disable();
    led_stripe_set_all(color_blue);
    QTimeEvt_disarm(&me->timeEvt);
    QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_SEC/10, BSP_TICKS_PER_SEC/10);
    return QM_ENTRY(&SumoHSM_RCWait_s);
}
/*${AOs::SumoHSM::SM::RCWait} */
static QState SumoHSM_RCWait_x(SumoHSM * const me) {
    QTimeEvt_disarm(&me->timeEvt);
    return QM_EXIT(&SumoHSM_RCWait_s);
}
/*${AOs::SumoHSM::SM::RCWait} */
static QState SumoHSM_RCWait(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::RCWait::START} */
        case START_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_RC_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_RCWait_x), /* exit */
                    Q_ACTION_CAST(&SumoHSM_RC_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            driving_enable();
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::RCWait::CHANGE_STATE_EVT} */
        case CHANGE_STATE_EVT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_Idle_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_RCWait_x), /* exit */
                    Q_ACTION_CAST(&SumoHSM_Idle_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            led_stripe_set_all(color_purple);
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::RCWait::TIMEOUT} */
        case TIMEOUT_SIG: {
            board_led_toggle();
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}

/*${AOs::SumoHSM::SM::StarStrategy} ........................................*/
/*${AOs::SumoHSM::SM::StarStrategy} */
static QState SumoHSM_StarStrategy_e(SumoHSM * const me) {
    drive(parameters.star_speed, parameters.star_speed);
    (void)me; /* unused parameter */
    return QM_ENTRY(&SumoHSM_StarStrategy_s);
}
/*${AOs::SumoHSM::SM::StarStrategy} */
static QState SumoHSM_StarStrategy(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::StarStrategy::LINE_CHANGED_FL, LINE_CHANGED_FR} */
        case LINE_CHANGED_FL_SIG: /* intentionally fall through */
        case LINE_CHANGED_FR_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_LineSubmachine_s, /* target submachine */
                {
                    Q_ACTION_CAST(&SumoHSM_line1_e), /* entry */
                    Q_ACTION_CAST(&SumoHSM_LineSubmachine_i), /* initial tran. */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::StarStrategy::STOP} */
        case STOP_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_AutoWait_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_AutoWait_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::StarStrategy::DIST_SENSOR_CHANGE} */
        case DIST_SENSOR_CHANGE_SIG: {
            if (distance_is_active(DIST_SENSOR_R)) {
               drive(80,-80);
            } else if (distance_is_active(DIST_SENSOR_FR)) {
               drive(80,0);
            } else if (distance_is_active(DIST_SENSOR_F)) {
               drive(100,100);
            } else if (distance_is_active(DIST_SENSOR_FL)) {
               drive(0,80);
            } else if (distance_is_active(DIST_SENSOR_L)) {
               drive(-80,80);
            } else {
               drive(60,60);
            }
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}

/*${AOs::SumoHSM::SM::AutoWait} ............................................*/
/*${AOs::SumoHSM::SM::AutoWait} */
static QState SumoHSM_AutoWait_e(SumoHSM * const me) {
    drive(0,0);
    driving_disable();
    board_led_on();
    led_stripe_set_strategy_color(me->strategy);
    led_stripe_set_pre_strategy_color(me->pre_strategy);
    return QM_ENTRY(&SumoHSM_AutoWait_s);
}
/*${AOs::SumoHSM::SM::AutoWait} */
static QState SumoHSM_AutoWait(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::AutoWait::START} */
        case START_SIG: {
            driving_enable();
            /*${AOs::SumoHSM::SM::AutoWait::START::[pre_strategy_0]} */
            if (me->pre_strategy == 0) {
                static struct {
                    QMState const *target;
                    QActionHandler act[3];
                } const tatbl_ = { /* tran-action table */
                    &SumoHSM_PreStrategy_s, /* target submachine */
                    {
                        Q_ACTION_CAST(&SumoHSM_pre_strategy_e), /* entry */
                        Q_ACTION_CAST(&SumoHSM_PreStrategy_EP0_ep), /* EP */
                        Q_ACTION_NULL /* zero terminator */
                    }
                };
                status_ = QM_TRAN_EP(&tatbl_);
            }
            /*${AOs::SumoHSM::SM::AutoWait::START::[pre_strategy_1]} */
            else if (me->pre_strategy == 1) {
                static struct {
                    QMState const *target;
                    QActionHandler act[3];
                } const tatbl_ = { /* tran-action table */
                    &SumoHSM_PreStrategy_s, /* target submachine */
                    {
                        Q_ACTION_CAST(&SumoHSM_pre_strategy_e), /* entry */
                        Q_ACTION_CAST(&SumoHSM_PreStrategy_EP1_ep), /* EP */
                        Q_ACTION_NULL /* zero terminator */
                    }
                };
                status_ = QM_TRAN_EP(&tatbl_);
            }
            /*${AOs::SumoHSM::SM::AutoWait::START::[pre_strategy_2]} */
            else if (me->pre_strategy == 2) {
                static struct {
                    QMState const *target;
                    QActionHandler act[3];
                } const tatbl_ = { /* tran-action table */
                    &SumoHSM_PreStrategy_s, /* target submachine */
                    {
                        Q_ACTION_CAST(&SumoHSM_pre_strategy_e), /* entry */
                        Q_ACTION_CAST(&SumoHSM_PreStrategy_EP2_ep), /* EP */
                        Q_ACTION_NULL /* zero terminator */
                    }
                };
                status_ = QM_TRAN_EP(&tatbl_);
            }
            /*${AOs::SumoHSM::SM::AutoWait::START::[pre_strategy_3]} */
            else if (me->pre_strategy == 3) {
                static struct {
                    QMState const *target;
                    QActionHandler act[3];
                } const tatbl_ = { /* tran-action table */
                    &SumoHSM_PreStrategy_s, /* target submachine */
                    {
                        Q_ACTION_CAST(&SumoHSM_pre_strategy_e), /* entry */
                        Q_ACTION_CAST(&SumoHSM_PreStrategy_EP3_ep), /* EP */
                        Q_ACTION_NULL /* zero terminator */
                    }
                };
                status_ = QM_TRAN_EP(&tatbl_);
            }
            else {
                status_ = QM_UNHANDLED();
            }
            break;
        }
        /*${AOs::SumoHSM::SM::AutoWait::CHANGE_STATE_EVT} */
        case CHANGE_STATE_EVT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_RCWait_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_RCWait_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::AutoWait::CHANGE_STRATEGY_EVT} */
        case CHANGE_STRATEGY_EVT_SIG: {
            SumoHSM_change_strategy(me);
            led_stripe_set_strategy_color(me->strategy);
            status_ = QM_HANDLED();
            break;
        }
        /*${AOs::SumoHSM::SM::AutoWait::CHANGE_PRE_STRATEGY_EVT} */
        case CHANGE_PRE_STRATEGY_EVT_SIG: {
            SumoHSM_change_pre_strategy(me);
            led_stripe_set_pre_strategy_color(me->pre_strategy);
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::StepsStrategy} .......................................*/
/*${AOs::SumoHSM::SM::StepsStrategy} */
static QState SumoHSM_StepsStrategy_e(SumoHSM * const me) {
    drive(0,0);
    uint32_t small_step_wait = parameters.step_wait_time_ms * BSP_TICKS_PER_MILISSEC;
    QTimeEvt_rearm(&me->timeEvt, small_step_wait);
    return QM_ENTRY(&SumoHSM_StepsStrategy_s);
}
/*${AOs::SumoHSM::SM::StepsStrategy} */
static QState SumoHSM_StepsStrategy_x(SumoHSM * const me) {
    QTimeEvt_disarm(&me->timeEvt);
    QTimeEvt_disarm(&me->timeEvt_2);
    return QM_EXIT(&SumoHSM_StepsStrategy_s);
}
/*${AOs::SumoHSM::SM::StepsStrategy} */
static QState SumoHSM_StepsStrategy(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::StepsStrategy::TIMEOUT} */
        case TIMEOUT_SIG: {
            drive(100,100);
            uint32_t small_step_advance_time = parameters.step_advance_time_ms * BSP_TICKS_PER_MILISSEC;
            QTimeEvt_rearm(&me->timeEvt_2, small_step_advance_time);
            status_ = QM_HANDLED();
            break;
        }
        /*${AOs::SumoHSM::SM::StepsStrategy::TIMEOUT_2} */
        case TIMEOUT_2_SIG: {
            drive(0,0);
            uint32_t small_step_wait = parameters.step_wait_time_ms * BSP_TICKS_PER_MILISSEC;
            QTimeEvt_rearm(&me->timeEvt, small_step_wait);
            status_ = QM_HANDLED();
            break;
        }
        /*${AOs::SumoHSM::SM::StepsStrategy::STOP} */
        case STOP_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_AutoWait_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_StepsStrategy_x), /* exit */
                    Q_ACTION_CAST(&SumoHSM_AutoWait_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::StepsStrategy::DIST_SENSOR_CHANGE} */
        case DIST_SENSOR_CHANGE_SIG: {
            QTimeEvt_disarm(&me->timeEvt);
            QTimeEvt_disarm(&me->timeEvt_2);

            if (distance_is_active(DIST_SENSOR_R)) {
               drive(80,-80);
            } else if (distance_is_active(DIST_SENSOR_FR)) {
               drive(80,0);
            } else if (distance_is_active(DIST_SENSOR_F)) {
               drive(100,100);
            } else if (distance_is_active(DIST_SENSOR_FL)) {
               drive(0,80);
            } else if (distance_is_active(DIST_SENSOR_L)) {
               drive(-80,80);
            } else {
               drive(0,0);
               uint32_t small_step_wait = parameters.step_wait_time_ms * BSP_TICKS_PER_MILISSEC;
               QTimeEvt_rearm(&me->timeEvt, small_step_wait);
            }


            status_ = QM_HANDLED();
            break;
        }
        /*${AOs::SumoHSM::SM::StepsStrategy::LINE_CHANGED_FL, LINE_CHANGED_FR} */
        case LINE_CHANGED_FL_SIG: /* intentionally fall through */
        case LINE_CHANGED_FR_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[4];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_LineSubmachine_s, /* target submachine */
                {
                    Q_ACTION_CAST(&SumoHSM_StepsStrategy_x), /* exit */
                    Q_ACTION_CAST(&SumoHSM_line2_e), /* entry */
                    Q_ACTION_CAST(&SumoHSM_LineSubmachine_i), /* initial tran. */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::RC} ..................................................*/
/*${AOs::SumoHSM::SM::RC} */
static QState SumoHSM_RC_e(SumoHSM * const me) {
    board_led_off();
    (void)me; /* unused parameter */
    return QM_ENTRY(&SumoHSM_RC_s);
}
/*${AOs::SumoHSM::SM::RC} */
static QState SumoHSM_RC(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::RC::RADIO_DATA} */
        case RADIO_DATA_SIG: {
            int coord_x = radio_service_get_channel(RADIO_CH1);
            int coord_y = radio_service_get_channel(RADIO_CH2);

            int mot1 = coord_y + coord_x;
            int mot2 = coord_y - coord_x;

            drive(mot1, mot2);
            status_ = QM_HANDLED();
            break;
        }
        /*${AOs::SumoHSM::SM::RC::STOP} */
        case STOP_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_RCWait_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_RCWait_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::line1} ...............................................*/
/*${AOs::SumoHSM::SM::line1} */
static QState SumoHSM_line1_e(SumoHSM * const me) {
    me->sub_LineSubmachine = &SumoHSM_line1_s; /* attach submachine */
    return QM_ENTRY(&SumoHSM_line1_s.super);
}
/*${AOs::SumoHSM::SM::line1} */
static QState SumoHSM_line1_XP1(SumoHSM * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { /* tran-action table */
        &SumoHSM_StarStrategy_s, /* target state */
        {
            Q_ACTION_CAST(&SumoHSM_LineSubmachine_x), /* submachine exit */
            Q_ACTION_CAST(&SumoHSM_StarStrategy_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    (void)me; /* unused parameter */
    return QM_TRAN(&tatbl_);
}
/*${AOs::SumoHSM::SM::line1} */
static QState SumoHSM_line1_STOP(SumoHSM * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { /* tran-action table */
        &SumoHSM_AutoWait_s, /* target state */
        {
            Q_ACTION_CAST(&SumoHSM_LineSubmachine_x), /* submachine exit */
            Q_ACTION_CAST(&SumoHSM_AutoWait_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    (void)me; /* unused parameter */
    return QM_TRAN(&tatbl_);
}
/*${AOs::SumoHSM::SM::line1} */
static QState SumoHSM_line1(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}

/*${AOs::SumoHSM::SM::line2} ...............................................*/
/*${AOs::SumoHSM::SM::line2} */
static QState SumoHSM_line2_e(SumoHSM * const me) {
    me->sub_LineSubmachine = &SumoHSM_line2_s; /* attach submachine */
    return QM_ENTRY(&SumoHSM_line2_s.super);
}
/*${AOs::SumoHSM::SM::line2} */
static QState SumoHSM_line2_XP1(SumoHSM * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { /* tran-action table */
        &SumoHSM_StepsStrategy_s, /* target state */
        {
            Q_ACTION_CAST(&SumoHSM_LineSubmachine_x), /* submachine exit */
            Q_ACTION_CAST(&SumoHSM_StepsStrategy_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    (void)me; /* unused parameter */
    return QM_TRAN(&tatbl_);
}
/*${AOs::SumoHSM::SM::line2} */
static QState SumoHSM_line2_STOP(SumoHSM * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { /* tran-action table */
        &SumoHSM_AutoWait_s, /* target state */
        {
            Q_ACTION_CAST(&SumoHSM_LineSubmachine_x), /* submachine exit */
            Q_ACTION_CAST(&SumoHSM_AutoWait_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    (void)me; /* unused parameter */
    return QM_TRAN(&tatbl_);
}
/*${AOs::SumoHSM::SM::line2} */
static QState SumoHSM_line2(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}

/*${AOs::SumoHSM::SM::pre_strategy} ........................................*/
/*${AOs::SumoHSM::SM::pre_strategy} */
static QState SumoHSM_pre_strategy_e(SumoHSM * const me) {
    me->sub_PreStrategy = &SumoHSM_pre_strategy_s; /* attach submachine */
    return SumoHSM_PreStrategy_e(me); /* enter submachine */
}
/*${AOs::SumoHSM::SM::pre_strategy} */
static QState SumoHSM_pre_strategy_XP1(SumoHSM * const me) {
    QState status_;
    /*${AOs::SumoHSM::SM::pre_strategy::XP1::[strategy_0]} */
    if (me->strategy == 0) {
        static struct {
            QMState const *target;
            QActionHandler act[3];
        } const tatbl_ = { /* tran-action table */
            &SumoHSM_StarStrategy_s, /* target state */
            {
                Q_ACTION_CAST(&SumoHSM_PreStrategy_x), /* submachine exit */
                Q_ACTION_CAST(&SumoHSM_StarStrategy_e), /* entry */
                Q_ACTION_NULL /* zero terminator */
            }
        };
        status_ = QM_TRAN(&tatbl_);
    }
    /*${AOs::SumoHSM::SM::pre_strategy::XP1::[else]} */
    else {
        static struct {
            QMState const *target;
            QActionHandler act[3];
        } const tatbl_ = { /* tran-action table */
            &SumoHSM_StepsStrategy_s, /* target state */
            {
                Q_ACTION_CAST(&SumoHSM_PreStrategy_x), /* submachine exit */
                Q_ACTION_CAST(&SumoHSM_StepsStrategy_e), /* entry */
                Q_ACTION_NULL /* zero terminator */
            }
        };
        status_ = QM_TRAN(&tatbl_);
    }
    return status_;
}
/*${AOs::SumoHSM::SM::pre_strategy} */
static QState SumoHSM_pre_strategy(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}

/*${AOs::SumoHSM::SM::LineSubmachine} ......................................*/
/*${AOs::SumoHSM::SM::LineSubmachine} */
static QState SumoHSM_LineSubmachine_x(SumoHSM * const me) {
    return QM_SM_EXIT(&me->sub_LineSubmachine->super);
}
/*${AOs::SumoHSM::SM::LineSubmachine::initial} */
static QState SumoHSM_LineSubmachine_i(SumoHSM * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { /* tran-action table */
        &SumoHSM_LineSubmachine_LineGoBack_s, /* target state */
        {
            Q_ACTION_CAST(&SumoHSM_LineSubmachine_LineGoBack_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    /*${AOs::SumoHSM::SM::LineSubmachine::initial} */
    return QM_TRAN_INIT(&tatbl_);
}
/*${AOs::SumoHSM::SM::LineSubmachine} */
static QState SumoHSM_LineSubmachine(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER_SUB(&me->sub_LineSubmachine->super);
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}

/*${AOs::SumoHSM::SM::LineSubmachine::LineGoBack} ..........................*/
/*${AOs::SumoHSM::SM::LineSubmachine::LineGoBack} */
static QState SumoHSM_LineSubmachine_LineGoBack_e(SumoHSM * const me) {
    drive(-parameters.reverse_speed, -parameters.reverse_speed);

    uint32_t reverse_time = BSP_TICKS_PER_MILISSEC * parameters.reverse_time_ms;

    if (adc_line_is_white(LINE_FL)){
        QTimeEvt_rearm(&me->timeEvt, reverse_time);
    } else {
        QTimeEvt_rearm(&me->timeEvt_2, reverse_time);
    }
    return QM_ENTRY(&SumoHSM_LineSubmachine_LineGoBack_s);
}
/*${AOs::SumoHSM::SM::LineSubmachine::LineGoBack} */
static QState SumoHSM_LineSubmachine_LineGoBack(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::LineSubmachine::LineGoBack::TIMEOUT} */
        case TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_LineSubmachine_LineTurnRight_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_LineSubmachine_LineTurnRight_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::LineSubmachine::LineGoBack::STOP} */
        case STOP_SIG: {
            static QMTranActTable const tatbl_ = { /* tran-action table */
                &SumoHSM_LineSubmachine_s, /* target submachine */
                {
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN_XP(me->sub_LineSubmachine->STOP, &tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::LineSubmachine::LineGoBack::TIMEOUT_2} */
        case TIMEOUT_2_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_LineSubmachine_LineTurnLeft_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_LineSubmachine_LineTurnLeft_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::LineSubmachine::LineTurnRight} .......................*/
/*${AOs::SumoHSM::SM::LineSubmachine::LineTurnRight} */
static QState SumoHSM_LineSubmachine_LineTurnRight_e(SumoHSM * const me) {
    drive(parameters.turn_speed, -parameters.turn_speed);
    uint32_t turn_time = BSP_TICKS_PER_MILISSEC * parameters.turn_180_time_ms * (0.6);
    QTimeEvt_rearm(&me->timeEvt, turn_time);
    return QM_ENTRY(&SumoHSM_LineSubmachine_LineTurnRight_s);
}
/*${AOs::SumoHSM::SM::LineSubmachine::LineTurnRight} */
static QState SumoHSM_LineSubmachine_LineTurnRight_x(SumoHSM * const me) {
    drive(0,0);
    (void)me; /* unused parameter */
    return QM_EXIT(&SumoHSM_LineSubmachine_LineTurnRight_s);
}
/*${AOs::SumoHSM::SM::LineSubmachine::LineTurnRight} */
static QState SumoHSM_LineSubmachine_LineTurnRight(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::LineSubmachine::LineTurnRight::TIMEOUT} */
        case TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_LineSubmachine_s, /* target submachine */
                {
                    Q_ACTION_CAST(&SumoHSM_LineSubmachine_LineTurnRight_x), /* exit */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN_XP(me->sub_LineSubmachine->XP1, &tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::LineSubmachine::LineTurnRight::DIST_SENSOR_CHANGE} */
        case DIST_SENSOR_CHANGE_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_LineSubmachine_s, /* target submachine */
                {
                    Q_ACTION_CAST(&SumoHSM_LineSubmachine_LineTurnRight_x), /* exit */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN_XP(me->sub_LineSubmachine->XP1, &tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::LineSubmachine::LineTurnRight::STOP} */
        case STOP_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_LineSubmachine_s, /* target submachine */
                {
                    Q_ACTION_CAST(&SumoHSM_LineSubmachine_LineTurnRight_x), /* exit */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN_XP(me->sub_LineSubmachine->STOP, &tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::LineSubmachine::LineTurnLeft} ........................*/
/*${AOs::SumoHSM::SM::LineSubmachine::LineTurnLeft} */
static QState SumoHSM_LineSubmachine_LineTurnLeft_e(SumoHSM * const me) {
    drive(-parameters.turn_speed, parameters.turn_speed);
    uint32_t turn_time = BSP_TICKS_PER_MILISSEC * parameters.turn_180_time_ms * (0.6);
    QTimeEvt_rearm(&me->timeEvt, turn_time);
    return QM_ENTRY(&SumoHSM_LineSubmachine_LineTurnLeft_s);
}
/*${AOs::SumoHSM::SM::LineSubmachine::LineTurnLeft} */
static QState SumoHSM_LineSubmachine_LineTurnLeft_x(SumoHSM * const me) {
    drive(0,0);
    (void)me; /* unused parameter */
    return QM_EXIT(&SumoHSM_LineSubmachine_LineTurnLeft_s);
}
/*${AOs::SumoHSM::SM::LineSubmachine::LineTurnLeft} */
static QState SumoHSM_LineSubmachine_LineTurnLeft(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::LineSubmachine::LineTurnLeft::TIMEOUT} */
        case TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_LineSubmachine_s, /* target submachine */
                {
                    Q_ACTION_CAST(&SumoHSM_LineSubmachine_LineTurnLeft_x), /* exit */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN_XP(me->sub_LineSubmachine->XP1, &tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::LineSubmachine::LineTurnLeft::DIST_SENSOR_CHANGE} */
        case DIST_SENSOR_CHANGE_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_LineSubmachine_s, /* target submachine */
                {
                    Q_ACTION_CAST(&SumoHSM_LineSubmachine_LineTurnLeft_x), /* exit */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN_XP(me->sub_LineSubmachine->XP1, &tatbl_);
            break;
        }
        /*${AOs::SumoHSM::SM::LineSubmachine::LineTurnLeft::STOP} */
        case STOP_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_LineSubmachine_s, /* target submachine */
                {
                    Q_ACTION_CAST(&SumoHSM_LineSubmachine_LineTurnLeft_x), /* exit */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN_XP(me->sub_LineSubmachine->STOP, &tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::PreStrategy} .........................................*/
/*${AOs::SumoHSM::SM::PreStrategy} */
static QState SumoHSM_PreStrategy_e(SumoHSM * const me) {
    QTimeEvt_disarm(&me->timeEvt);
    QTimeEvt_disarm(&me->timeEvt_2);
    return QM_ENTRY(&SumoHSM_PreStrategy_s);
}
/*${AOs::SumoHSM::SM::PreStrategy} */
static QState SumoHSM_PreStrategy_x(SumoHSM * const me) {
    return QM_SM_EXIT(&me->sub_PreStrategy->super);
}
/*${AOs::SumoHSM::SM::PreStrategy} */
static QState SumoHSM_PreStrategy(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER_SUB(&me->sub_PreStrategy->super);
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}
/*${AOs::SumoHSM::SM::PreStrategy::EP-EP0} */
static QState SumoHSM_PreStrategy_EP0_ep(SumoHSM * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { /* tran-action table */
        &SumoHSM_PreStrategy_PreStrategy_0_s, /* target state */
        {
            Q_ACTION_CAST(&SumoHSM_PreStrategy_PreStrategy_0_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    return QM_TRAN_EP(&tatbl_);
}
/*${AOs::SumoHSM::SM::PreStrategy::EP-EP1} */
static QState SumoHSM_PreStrategy_EP1_ep(SumoHSM * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { /* tran-action table */
        &SumoHSM_PreStrategy_PreStrategy_1_s, /* target state */
        {
            Q_ACTION_CAST(&SumoHSM_PreStrategy_PreStrategy_1_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    return QM_TRAN_EP(&tatbl_);
}
/*${AOs::SumoHSM::SM::PreStrategy::EP-EP2} */
static QState SumoHSM_PreStrategy_EP2_ep(SumoHSM * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { /* tran-action table */
        &SumoHSM_PreStrategy_PreStrategy_2_s, /* target state */
        {
            Q_ACTION_CAST(&SumoHSM_PreStrategy_PreStrategy_2_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    return QM_TRAN_EP(&tatbl_);
}
/*${AOs::SumoHSM::SM::PreStrategy::EP-EP3} */
static QState SumoHSM_PreStrategy_EP3_ep(SumoHSM * const me) {
    static QMTranActTable const tatbl_ = { /* tran-action table */
        &SumoHSM_PreStrategy_PreStrategy_3_s, /* target state */
        {
            Q_ACTION_NULL /* zero terminator */
        }
    };
    return QM_TRAN_EP(&tatbl_);
}

/*${AOs::SumoHSM::SM::PreStrategy::PreStrategy_0} ..........................*/
/*${AOs::SumoHSM::SM::PreStrategy::PreStrategy_0} */
static QState SumoHSM_PreStrategy_PreStrategy_0_e(SumoHSM * const me) {
    drive(100,100);
    QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_MILISSEC * 10, 0);
    return QM_ENTRY(&SumoHSM_PreStrategy_PreStrategy_0_s);
}
/*${AOs::SumoHSM::SM::PreStrategy::PreStrategy_0} */
static QState SumoHSM_PreStrategy_PreStrategy_0(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::PreStrategy::PreStrategy_0::TIMEOUT} */
        case TIMEOUT_SIG: {
            static QMTranActTable const tatbl_ = { /* tran-action table */
                &SumoHSM_PreStrategy_s, /* target submachine */
                {
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN_XP(me->sub_PreStrategy->XP1, &tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::PreStrategy::PreStrategy_2} ..........................*/
/*${AOs::SumoHSM::SM::PreStrategy::PreStrategy_2} */
static QState SumoHSM_PreStrategy_PreStrategy_2_e(SumoHSM * const me) {
    drive(60,-60);
    QTimeEvt_rearm(&me->timeEvt, BSP_TICKS_PER_MILISSEC * parameters.turn_180_time_ms * (0.2));
    return QM_ENTRY(&SumoHSM_PreStrategy_PreStrategy_2_s);
}
/*${AOs::SumoHSM::SM::PreStrategy::PreStrategy_2} */
static QState SumoHSM_PreStrategy_PreStrategy_2(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::PreStrategy::PreStrategy_2::TIMEOUT} */
        case TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_PreStrategy_pre_strategy_2_sub1_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_PreStrategy_pre_strategy_2_sub1_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::PreStrategy::PreStrategy_3} ..........................*/
/*${AOs::SumoHSM::SM::PreStrategy::PreStrategy_3} */
static QState SumoHSM_PreStrategy_PreStrategy_3(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}

/*${AOs::SumoHSM::SM::PreStrategy::PreStrategy_1} ..........................*/
/*${AOs::SumoHSM::SM::PreStrategy::PreStrategy_1} */
static QState SumoHSM_PreStrategy_PreStrategy_1_e(SumoHSM * const me) {
    drive(-60,60);
    QTimeEvt_rearm(&me->timeEvt, BSP_TICKS_PER_MILISSEC * parameters.turn_180_time_ms * (0.2));
    return QM_ENTRY(&SumoHSM_PreStrategy_PreStrategy_1_s);
}
/*${AOs::SumoHSM::SM::PreStrategy::PreStrategy_1} */
static QState SumoHSM_PreStrategy_PreStrategy_1(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::PreStrategy::PreStrategy_1::TIMEOUT} */
        case TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_PreStrategy_pre_strategy_1_sub1_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_PreStrategy_pre_strategy_1_sub1_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::PreStrategy::pre_strategy_1_sub2} ....................*/
/*${AOs::SumoHSM::SM::PreStrategy::pre_strategy_1_sub2} */
static QState SumoHSM_PreStrategy_pre_strategy_1_sub2_e(SumoHSM * const me) {
    drive(100,-100);
    QTimeEvt_rearm(&me->timeEvt, BSP_TICKS_PER_MILISSEC * parameters.turn_180_time_ms * (0.4));
    return QM_ENTRY(&SumoHSM_PreStrategy_pre_strategy_1_sub2_s);
}
/*${AOs::SumoHSM::SM::PreStrategy::pre_strategy_1_sub2} */
static QState SumoHSM_PreStrategy_pre_strategy_1_sub2(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::PreStrategy::pre_strategy_1_s~::TIMEOUT} */
        case TIMEOUT_SIG: {
            static QMTranActTable const tatbl_ = { /* tran-action table */
                &SumoHSM_PreStrategy_s, /* target submachine */
                {
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN_XP(me->sub_PreStrategy->XP1, &tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::PreStrategy::pre_strategy_1_sub1} ....................*/
/*${AOs::SumoHSM::SM::PreStrategy::pre_strategy_1_sub1} */
static QState SumoHSM_PreStrategy_pre_strategy_1_sub1_e(SumoHSM * const me) {
    drive(100,100);
    QTimeEvt_rearm(&me->timeEvt, BSP_TICKS_PER_MILISSEC * 500);
    return QM_ENTRY(&SumoHSM_PreStrategy_pre_strategy_1_sub1_s);
}
/*${AOs::SumoHSM::SM::PreStrategy::pre_strategy_1_sub1} */
static QState SumoHSM_PreStrategy_pre_strategy_1_sub1(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::PreStrategy::pre_strategy_1_s~::TIMEOUT} */
        case TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_PreStrategy_pre_strategy_1_sub2_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_PreStrategy_pre_strategy_1_sub2_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::PreStrategy::pre_strategy_2_sub1} ....................*/
/*${AOs::SumoHSM::SM::PreStrategy::pre_strategy_2_sub1} */
static QState SumoHSM_PreStrategy_pre_strategy_2_sub1_e(SumoHSM * const me) {
    drive(100,100);
    QTimeEvt_rearm(&me->timeEvt, BSP_TICKS_PER_MILISSEC * 500);
    return QM_ENTRY(&SumoHSM_PreStrategy_pre_strategy_2_sub1_s);
}
/*${AOs::SumoHSM::SM::PreStrategy::pre_strategy_2_sub1} */
static QState SumoHSM_PreStrategy_pre_strategy_2_sub1(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::PreStrategy::pre_strategy_2_s~::TIMEOUT} */
        case TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &SumoHSM_PreStrategy_pre_strategy_2_sub2_s, /* target state */
                {
                    Q_ACTION_CAST(&SumoHSM_PreStrategy_pre_strategy_2_sub2_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/*${AOs::SumoHSM::SM::PreStrategy::pre_strategy_2_sub2} ....................*/
/*${AOs::SumoHSM::SM::PreStrategy::pre_strategy_2_sub2} */
static QState SumoHSM_PreStrategy_pre_strategy_2_sub2_e(SumoHSM * const me) {
    drive(-100,100);
    QTimeEvt_rearm(&me->timeEvt, BSP_TICKS_PER_MILISSEC * parameters.turn_180_time_ms * (0.4));
    return QM_ENTRY(&SumoHSM_PreStrategy_pre_strategy_2_sub2_s);
}
/*${AOs::SumoHSM::SM::PreStrategy::pre_strategy_2_sub2} */
static QState SumoHSM_PreStrategy_pre_strategy_2_sub2(SumoHSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::SumoHSM::SM::PreStrategy::pre_strategy_2_s~::TIMEOUT} */
        case TIMEOUT_SIG: {
            static QMTranActTable const tatbl_ = { /* tran-action table */
                &SumoHSM_PreStrategy_s, /* target submachine */
                {
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN_XP(me->sub_PreStrategy->XP1, &tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::SumoHSM} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

#ifdef Q_SPY

void sumoHSM_update_qs_dict(){

    QS_OBJ_DICTIONARY(&l_sumo_hsm);
    QS_OBJ_DICTIONARY(&l_sumo_hsm.timeEvt);
    QS_OBJ_DICTIONARY(&l_sumo_hsm.timeEvt_2);
    QS_OBJ_DICTIONARY(&l_sumo_hsm.buzzerTimeEvt);
    QS_OBJ_DICTIONARY(&l_sumo_hsm.strategy);

    QS_SIG_DICTIONARY(TIMEOUT_SIG,     (void *)0);
    QS_SIG_DICTIONARY(TIMEOUT_2_SIG, (void *)0);
    QS_SIG_DICTIONARY(PLAY_BUZZER_SIG,    (void *)0);
    QS_SIG_DICTIONARY(START_SIG,  (void *)0);
    QS_SIG_DICTIONARY(CHANGE_STATE_EVT_SIG,  (void *)0);
    QS_SIG_DICTIONARY(CHANGE_STRATEGY_EVT_SIG,  (void *)0);
    QS_SIG_DICTIONARY(CHANGE_PRE_STRATEGY_EVT_SIG,  (void *)0);
    QS_SIG_DICTIONARY(STOP_SIG,  (void *)0);
    QS_SIG_DICTIONARY(LINE_CHANGED_FL_SIG,  (void *)0);
    QS_SIG_DICTIONARY(LINE_CHANGED_FR_SIG,  (void *)0);
    QS_SIG_DICTIONARY(LINE_CHANGED_BL_SIG,  (void *)0);
    QS_SIG_DICTIONARY(LINE_CHANGED_BR_SIG,  (void *)0);
    QS_SIG_DICTIONARY(DIST_SENSOR_CHANGE_SIG,  (void *)0);
    QS_SIG_DICTIONARY(RADIO_DATA_SIG,  (void *)0);
    QS_SIG_DICTIONARY(BUTTON_SIG,  (void *)0);
    QS_SIG_DICTIONARY(BLE_DATA_SIG,  (void *)0);
    QS_SIG_DICTIONARY(LOW_BATTERY_SIG,  (void *)0);
    QS_SIG_DICTIONARY(TIMEOUT_SEND_BLE_SIG,  (void *)0);


}

#endif
